---
- hosts: localhost
  connection: local
  tasks:
  - name: instal http and php #on MacOS
    package:
      name: 
        - "{{ httpd_package }}"
        - "{{ php_package }}"
      state: latest
      update_homebrew: yes
  

